# Laboratorio 2: Bases y coordenadas

**Curso:** Matemática aplicada a la computación  
**Tema:** Bases, representación de polinomios y coordenadas  
**Herramienta:** Python / NumPy

## Objetivos
1. Verificar computacionalmente si un conjunto forma una base.
2. Representar polinomios mediante vectores de coeficientes.
3. Calcular coordenadas respecto de distintas bases.

## 1. Verificación de una base de $\mathbb{R}^5$

Considere
$$
\begin{aligned}
v_1&=(1,1,0,1,2), & v_2&=(0,1,1,0,1),\\
v_3&=(1,0,1,1,0), & v_4&=(2,1,0,0,1),\\
v_5&=(1,2,1,1,1).
\end{aligned}
$$

¿Es $\mathcal B=\{v_1,v_2,v_3,v_4,v_5\}$ una base de $\mathbb R^5$?

Como hay cinco vectores en un espacio de dimensión $5$, basta verificar que sean linealmente independientes. Construimos la matriz
$$
A=\begin{pmatrix}|&|&|&|&|\\v_1&v_2&v_3&v_4&v_5\\|&|&|&|&|\end{pmatrix}.
$$
Entonces
$$
\mathcal B\text{ es base de }\mathbb R^5
\Longleftrightarrow \operatorname{rango}(A)=5 \Longleftrightarrow \det(A)\neq0.
$$

In [1]:
import numpy as np

v1 = np.array([1, 1, 0, 1, 2])
v2 = np.array([0, 1, 1, 0, 1])
v3 = np.array([1, 0, 1, 1, 0])
v4 = np.array([2, 1, 0, 0, 1])
v5 = np.array([1, 2, 1, 1, 1])
# v5 = v1+v2

A = np.column_stack((v1, v2, v3, v4, v5))

print(A)
print("Rango =", np.linalg.matrix_rank(A))
print("Determinante =", np.linalg.det(A))

[[1 0 1 2 1]
 [1 1 0 1 2]
 [0 1 1 0 1]
 [1 0 1 0 1]
 [2 1 0 1 1]]
Rango = 5
Determinante = 7.999999999999998


**Para discutir:** ¿qué ocurriría con el rango y el determinante si reemplazáramos $v_5$ por $v_1+v_2$?

Con el sgte codigo vamos a comprobar que pasaria

In [9]:
import numpy as np

v1 = np.array([1, 1, 0, 1, 2])
v2 = np.array([0, 1, 1, 0, 1])
v3 = np.array([1, 0, 1, 1, 0])
v4 = np.array([2, 1, 0, 0, 1])

v5_nuevo = v1 + v2

A_modificada = np.column_stack((v1, v2, v3, v4, v5_nuevo))

print("rango modif =", np.linalg.matrix_rank(A_modificada))
print("determinate  modif =", np.linalg.det(A_modificada))

rango modificado = 4
determinate  modificado = 0.0


- Como se vio el determinte resulto ser 0, esto te dio ya que ahora L.I
- El rango disminuiria a 4, ya que los vectores ya no serian L.I.

## 2. Polinomios como vectores

Un polinomio
$$
p(x)=a+bx+cx^2
$$
puede identificarse con su vector de coeficientes:
$$
a+bx+cx^2\longleftrightarrow(a,b,c).
$$

Esta correspondencia preserva suma y multiplicación por escalares. En general,
$$
a_0+a_1x+\cdots+a_nx^n
\longleftrightarrow
(a_0,a_1,\ldots,a_n).
$$

Por ello, los problemas de independencia lineal y bases en $P_n[x]$ pueden estudiarse mediante vectores de coeficientes.

### Ejemplo en $P_3[x]$

Considere
$$
p_1=1+x,\qquad p_2=x+x^2,\qquad
p_3=x^2+x^3,\qquad p_4=1-x+x^3.
$$

Respecto del orden $(1,x,x^2,x^3)$:
$$
p_1\leftrightarrow(1,1,0,0),\quad
p_2\leftrightarrow(0,1,1,0),
$$
$$
p_3\leftrightarrow(0,0,1,1),\quad
p_4\leftrightarrow(1,-1,0,1).
$$

Verifique si $\mathcal B=\{p_1,p_2,p_3,p_4\}$ es una base de $P_3[x]$.

In [2]:
p1 = np.array([1, 1, 0, 0])
p2 = np.array([0, 1, 1, 0])
p3 = np.array([0, 0, 1, 1])
p4 = np.array([1, -1, 0, 1])

P = np.column_stack((p1, p2, p3, p4))

print(P)
print("Rango =", np.linalg.matrix_rank(P))
print("Determinante =", np.linalg.det(P))

[[ 1  0  0  1]
 [ 1  1  0 -1]
 [ 0  1  1  0]
 [ 0  0  1  1]]
Rango = 4
Determinante = -1.0


Como $\dim(P_3[x])=4$, cuatro polinomios linealmente independientes forman una base.

$$
\boxed{\text{Podemos estudiar polinomios mediante sus vectores de coeficientes.}}
$$

## 3. Coordenadas respecto de distintas bases

Considere las bases de $\mathbb R^3$
$$
\mathcal B=\{(1,1,0),(0,1,1),(1,0,1)\}
$$
y
$$
\mathcal C=\{(1,0,0),(1,1,0),(1,1,1)\}.
$$

Generaremos un vector aleatorio $x\in\mathbb R^3$ y encontraremos sus coordenadas en ambas bases.

Si
$$
[x]_{\mathcal B}=
\begin{pmatrix}\alpha_1\\\alpha_2\\\alpha_3\end{pmatrix},
$$
entonces
$$
x=\alpha_1b_1+\alpha_2b_2+\alpha_3b_3.
$$
Si $B$ tiene como columnas los vectores de $\mathcal B$, debemos resolver
$$
B[x]_{\mathcal B}=x.
$$

In [3]:
B = np.column_stack(([1, 1, 0], [0, 1, 1], [1, 0, 1]))
C = np.column_stack(([1, 0, 0], [1, 1, 0], [1, 1, 1]))

print("Rango de B =", np.linalg.matrix_rank(B))
print("Rango de C =", np.linalg.matrix_rank(C))

rng = np.random.default_rng(123)
x = rng.integers(-5, 6, size=3)
print("x =", x)

coord_B = np.linalg.solve(B, x)
coord_C = np.linalg.solve(C, x)

print("[x]_B =", coord_B)
print("[x]_C =", coord_C)

Rango de B = 3
Rango de C = 3
x = [-5  2  1]
[x]_B = [-2.  4. -3.]
[x]_C = [-7.  1.  1.]


Aunque las coordenadas sean diferentes, ambas describen el mismo vector:
$$
x=B[x]_{\mathcal B}=C[x]_{\mathcal C}.
$$

In [4]:
x_desde_B = B @ coord_B
x_desde_C = C @ coord_C

print("x =", x)
print("B[x]_B =", x_desde_B)
print("C[x]_C =", x_desde_C)

print("¿B[x]_B = x?", np.allclose(x_desde_B, x))
print("¿C[x]_C = x?", np.allclose(x_desde_C, x))

x = [-5  2  1]
B[x]_B = [-5.  2.  1.]
C[x]_C = [-5.  2.  1.]
¿B[x]_B = x? True
¿C[x]_C = x? True


# Ejercicio propuesto

Considere
$$
\mathcal B=\{1+x-2x^2+x^3,\;1+x-x^2+5x^3,\;3-x^2+x^3,\;1+5x-3x^2+x^3\}.
$$

1. Represente los polinomios mediante vectores de $\mathbb R^4$.
2. Utilice `np.linalg.matrix_rank` para verificar que $\mathcal B$ es una base de $P_3[x]$.
3. Genere aleatoriamente
$$
p(x)=a+bx+cx^2+dx^3,\qquad a,b,c,d\in\{-5,\ldots,5\},
$$
y encuentre $[p]_{\mathcal B}$.

In [8]:
#Desarrolle aquí el ejercicio 1.

 #definicion de los vectores

p1 = np.array([1, 1, -2, 1])
p2 = np.array([1, 1, -1, 5])
p3 = np.array([3, 0, -1, 1])
p4 = np.array([1, 5, -3, 1])


B_poly = np.column_stack((p1, p2, p3, p4))
print("Rango =", np.linalg.matrix_rank(B_poly))

rng = np.random.default_rng(123)
p = rng.integers(-5,6, size = 4 )

coord_p = np.linalg.solve(B_poly, p)
print("[p]_B =", coord_p)


Rango = 4
[p]_B = [-0.26315789 -0.76315789 -1.52631579  0.60526316]


## Conclusiones

En este laboratorio observamos que:

- una base permite representar de manera única los vectores de un espacio;
- los polinomios pueden estudiarse mediante sus vectores de coeficientes;
- las coordenadas dependen de la base, aunque el vector representado sea el mismo.